# Generated by Django 6.0.2 on 2026-02-09 08:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('agent_id', models.CharField(max_length=100, unique=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('operating_system', models.CharField(blank=True, max_length=255)),
                ('cpu_model', models.CharField(blank=True, max_length=255)),
                ('ram_total', models.CharField(blank=True, max_length=50)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('private_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_online', models.BooleanField(default=False)),
                ('last_login_user', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmm.devicegroup')),
            ],
        ),
    ]
