# Generated by Django 6.0.2 on 2026-02-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='private_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='public_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
