# Generated by Django 6.0.2 on 2026-02-09 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmm', '0002_alter_agent_private_ip_alter_agent_public_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='alert_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='custom_dns',
            field=models.CharField(default='8.8.8.8', max_length=50),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_crucial',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('ram_usage', models.FloatField(default=0.0)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmm.agent')),
            ],
        ),
    ]
