# Generated by Django 6.0.2 on 2026-02-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmm', '0003_agent_alert_email_agent_custom_dns_agent_is_crucial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancelog',
            name='disk_usage',
            field=models.FloatField(default=0.0),
        ),
    ]
