from django.db import models
from django.utils import timezone

class DeviceGroup(models.Model):
    """
    Categorizes devices (e.g., 'Office PCs', 'Servers', 'Remote Laptops')
    [cite: 7, 16, 28]
    """
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class Agent(models.Model):
    """
    Represents a single computer or device managed by the RMM system.
    Stores hardware specs, current status, and configuration.
    [cite: 1, 10]
    """
    # --- Identification ---
    hostname = models.CharField(max_length=255)
    agent_id = models.CharField(max_length=100, unique=True) # Unique ID generated by the Agent script
    serial_number = models.CharField(max_length=100, blank=True) # 
    mac_address = models.CharField(max_length=50, blank=True) # 
    
    # --- Categories & Sorting ---
    group = models.ForeignKey(DeviceGroup, on_delete=models.SET_NULL, null=True, blank=True) # [cite: 7]
    is_favorite = models.BooleanField(default=False) # [cite: 41]
    notes = models.TextField(blank=True) # [cite: 40]
    
    # --- Hardware Details  ---
    operating_system = models.CharField(max_length=255, blank=True)
    cpu_model = models.CharField(max_length=255, blank=True)
    ram_total = models.CharField(max_length=50, blank=True)
    
    # --- Network Details ---
    # Changed to CharField to avoid validation errors if Agent sends "Unknown" or "Checking..."
    public_ip = models.CharField(max_length=50, blank=True, null=True) # 
    private_ip = models.CharField(max_length=50, blank=True, null=True) # 
    
    # --- Status Monitoring ---
    last_seen = models.DateTimeField(default=timezone.now)
    is_online = models.BooleanField(default=False) # [cite: 27]
    last_login_user = models.CharField(max_length=100, blank=True) # 
    
    # --- Monitoring Configuration (Function 3) ---
    is_crucial = models.BooleanField(default=False) # [cite: 32] - Mark important for alerts
    custom_dns = models.CharField(max_length=50, default="8.8.8.8") # [cite: 30] - DNS setting
    alert_email = models.EmailField(blank=True, null=True) # [cite: 33] - Who to email if offline

    def __str__(self):
        return f"{self.hostname} ({self.private_ip})"

class PerformanceLog(models.Model):
    """
    Stores historical performance data for generating graphs.
    
    """
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    # Metrics recorded by the Agent
    cpu_usage = models.FloatField(default=0.0) # Percentage
    ram_usage = models.FloatField(default=0.0) # Percentage
    latency_ms = models.FloatField(default=0.0) # Milliseconds (Ping) 
    
    def __str__(self):
        return f"{self.agent.hostname} @ {self.timestamp.strftime('%H:%M:%S')}"